# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('surname', models.CharField(max_length=200)),
                ('given_name', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=500)),
                ('telephone', models.CharField(max_length=12)),
                ('weight', models.CharField(max_length=10)),
                ('bday', models.DateField()),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20)),
                ('contact_form', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('SAR_incident_no', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('date_of_injury', models.DateTimeField()),
                ('place_first_seen', models.CharField(max_length=50)),
                ('transferred_to', models.CharField(max_length=100)),
                ('transferred_from', models.CharField(max_length=100)),
                ('consent', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('chief_complaint', models.TextField(max_length=5000)),
                ('mechanism_of_injury', models.TextField(max_length=5000)),
                ('found_on_examination', models.TextField(max_length=5000)),
                ('symptoms', models.TextField(max_length=500)),
                ('allergies', models.TextField(max_length=500)),
                ('medications', models.TextField(max_length=500)),
                ('pertinent_past_history', models.TextField(max_length=500)),
                ('last_meal', models.TextField(max_length=500)),
                ('events_prior_emergency', models.TextField(max_length=500)),
                ('onset', models.CharField(max_length=50)),
                ('provocation', models.CharField(max_length=50)),
                ('quality', models.CharField(max_length=50)),
                ('radiations', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50)),
                ('time_sec_assessment', models.TimeField()),
                ('head_neck', models.TextField(max_length=1000)),
                ('chest', models.TextField(max_length=1000)),
                ('cardio_vascular', models.TextField(max_length=1000)),
                ('abdomen', models.TextField(max_length=1000)),
                ('pelvis', models.TextField(max_length=1000)),
                ('back', models.TextField(max_length=1000)),
                ('extremities', models.TextField(max_length=1000)),
                ('neurological', models.TextField(max_length=1000)),
                ('blood_loss', models.TextField(max_length=1000)),
                ('o2_mask_type', models.TextField(max_length=1000)),
                ('time_onn_of', models.TimeField()),
                ('flow_rate', models.TextField(max_length=1000)),
                ('airway_type', models.CharField(choices=[('Oro', 'Oro'), ('Naso', 'Naso')], max_length=50)),
                ('airway_size', models.IntegerField()),
                ('treatment_plan', models.TextField(max_length=10000)),
                ('basket_litter', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('spine_board', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('scoop', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('ked', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('hard_collar', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('traction_splint', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('splint', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('float_blanket', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('inhalation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('hot_cold_pack', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('burn_dressing', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('entonox', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('aed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('other', models.TextField(max_length=1000)),
                ('personal_effects', models.TextField(max_length=10000)),
                ('rescue_sp_name', models.CharField(max_length=50)),
                ('rs_sign', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('date_rs', models.DateField()),
                ('vessel', models.TextField(max_length=5000)),
                ('co_sign', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('date_co', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Physicians_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.TimeField()),
                ('orders', models.TextField(max_length=500)),
                ('doctors_name', models.TextField(max_length=500)),
                ('facility', models.TextField(max_length=500)),
                ('ph_sar_inc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCR.PatientRecord')),
            ],
        ),
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_on_off', models.TimeField()),
                ('medications', models.TextField(max_length=500)),
                ('results', models.TextField(max_length=500)),
                ('md_sar_inc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCR.PatientRecord')),
            ],
        ),
        migrations.CreateModel(
            name='RescueSpecialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=50)),
                ('emailid', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vital_Signs',
            fields=[
                ('pt_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_obsvd', models.TimeField(blank=True, null=True)),
                ('loc', models.TextField(blank=True, max_length=500)),
                ('pulse', models.TextField(blank=True, max_length=500)),
                ('respiration', models.TextField(blank=True, max_length=500)),
                ('pupils', models.TextField(blank=True, max_length=500)),
                ('skin', models.TextField(blank=True, max_length=500)),
                ('bpdate', models.DateField(null=True)),
                ('bp', models.TextField(blank=True, max_length=500)),
                ('systolic', models.TextField(blank=True, max_length=500)),
                ('diastolic', models.TextField(blank=True, max_length=500)),
                ('temp', models.TextField(blank=True, max_length=500)),
                ('sat_perc', models.IntegerField(null=True)),
                ('pt_sar_inc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCR.PatientRecord')),
            ],
        ),
    ]
